### ISSUE TITLE
Improve transparency metrics

### ISSUE THREAD

**Issue by bkhall** [helium/helium-vote#37]
The votes only show totals of FOR and AGAINST.

Add metrics to report vote totals (not HNT) in each case (for and against) from Validators and Hotspot owners.

The idea is to publicly show how lopsided the current notion of voting power is, in favor of Validators. The bigger a wallet gets, the easier it is to steer a vote in a direction that favors one's own interests. That's the opposite of decentralization.

**Comment by jthiller** [comment]
![Screen Shot 2022-02-17 at 5 41 51 PM](https://user-images.githubusercontent.com/1965053/154601501-865c187a-65ca-49a6-95d3-ecc125c59e83.png)
These values represent the total number of wallets that have voted.

A wallet can have hotspots, validators, or both. Additionally, a user may have 10k HNT but not have it staked as a validator. 
As you'll note from this list, many large holders of the token do not stake as validators. https://explorer.helium.com/accounts/richest

As a further note, wallet-weighted voting has not been implemented because wallet creation is trivial and free.

**Comment by bkhall** [comment]
All those points are understood...
But your graphic illustrates the issue at hand.

**Comment by bkhall** [comment]
@jthiller 
I must have fat fingered the close button. Could you reopen it so it can be properly considered by the team?
